-- Add social media columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS facebook VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS instagram VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tiktok VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(20) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS youtube VARCHAR(255) DEFAULT NULL;

-- Update existing records to use phone as whatsapp if not set
UPDATE users SET whatsapp = phone WHERE whatsapp IS NULL AND phone IS NOT NULL;
